# CMake generated Testfile for 
# Source directory: /home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch
# Build directory: /home/dwijesek/git/ns-allinone-3.42/ns-3.42/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_ip-multicastGrokv3 "ns3.42-ip-multicastGrokv3-default")
set_tests_properties(ctest-scratch_ip-multicastGrokv3 PROPERTIES  WORKING_DIRECTORY "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_ip_multicast "ns3.42-ip_multicast-default")
set_tests_properties(ctest-scratch_ip_multicast PROPERTIES  WORKING_DIRECTORY "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_ip_multicastv1 "ns3.42-ip_multicastv1-default")
set_tests_properties(ctest-scratch_ip_multicastv1 PROPERTIES  WORKING_DIRECTORY "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_ip_multicastv2 "ns3.42-ip_multicastv2-default")
set_tests_properties(ctest-scratch_ip_multicastv2 PROPERTIES  WORKING_DIRECTORY "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_phy_multicast "ns3.42-phy_multicast-default")
set_tests_properties(ctest-scratch_phy_multicast PROPERTIES  WORKING_DIRECTORY "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_phy_multicast_new "ns3.42-phy_multicast_new-default")
set_tests_properties(ctest-scratch_phy_multicast_new PROPERTIES  WORKING_DIRECTORY "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.42-scratch-simulator-default")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_unicast "ns3.42-unicast-default")
set_tests_properties(ctest-scratch_unicast PROPERTIES  WORKING_DIRECTORY "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.42-scratch-subdir-default")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build/scratch/subdir/" _BACKTRACE_TRIPLES "/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;109;create_scratch;/home/dwijesek/git/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
subdirs("nested-subdir")
