version: "3.9"


# networks:
#   5g-core:
#     external: false
#     name: 5g-net
networks:
  5g-core:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24

services:
  ue:
    build: ./ue
    container_name: ue
    network_mode: "service:upf"
    cap_add:
      - NET_ADMIN
    
  gnb:
    build: ./gnb
    container_name: gnb
    networks:
      - 5g-core
    ports:
      - "5001:5001"
    depends_on:
      - ue
      - amf

  amf:
    build: ./amf
    container_name: amf
    networks:
      - 5g-core
    ports:
      - "5002:5002"
    depends_on:
      - ausf
      - smf

  ausf:
    build: ./ausf
    container_name: ausf
    networks:
      - 5g-core
    ports:
      - "5003:5003"
    depends_on:
      - udm

  udm:
    build: ./udm
    container_name: udm
    networks:
      - 5g-core
    ports:
      - "5004:5004"

  smf:
    build: ./smf
    container_name: smf
    networks:
      - 5g-core
    ports:
      - "5005:5005"
    depends_on:
      - upf

  upf:
    # Add these capabilities
    build: ./upf
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - /lib/moudles:/lib/modules    
    container_name: upf
    networks:
      - 5g-core
    ports:
      - "5006:5006"
    